spring:
  application:
    name: ad-gateway
server:
  port: 8801
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8800/eureka/
zuul:
  prefix: /ad
  routes:
    sponsor:
      path: /sponsor/**
      serviceId: eureka-client-ad-sponsor
      strip-prefix: false
