spring:
  application:
    name: eureka-client-ad-sponsor
  jpa:
    show-sql: true
    hibernate:
      # 手动创建表
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/ad?serverTimezone=GMT%2B8
    username: admin
    password: Lc.123456
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8802
  servlet:
    context-path: /sponsor
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8800/eureka/
